name: Build-Test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CORE_VERSION: 6.x.x
      BUILD_CONFIGURATION: Release
    steps:
      - name: checkear el repositorio
        uses: actions/checkout@v3
      
      - name: crear carpeta publish
        run: mkdir publish
      - name: crear archivo en publish
        run: cd publish && touch main.py
     
      - name: mostrar directorio
        run: ls
      - name: comprimir publish
        run: zip publish.zip publish
        
      - name: mostrar directorio
        run: ls
      
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: ./publish.zip
        

     
        
          
    
    
