name: Build-Test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CORE_VERSION: 6.x.x
    steps:
      - name: checkear el repositorio
        uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK ( ${{ env.DOTNET_CORE_VERSION }} )
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      
    
