name: Build-Test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CORE_VERSION: 6.x.x
      BUILD_CONFIGURATION: Release
    steps:
      - name: checkear el repositorio
        uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK ( ${{ env.DOTNET_CORE_VERSION }} )
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Restore Packages
        run: dotnet restore 
        
      - name: Build - .NET Core ${{ env.DOTNET_CORE_VERSION }}
        run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }}
      - name: Publish
        run: dotnet publish
        
      
    
